name: regression-cookbook-py
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - statsmodels
prefix: /Users/benchen/miniconda3/envs/regression-cookbook-py
